devices:
  uut:
    1:
      config: 'c3745'
      sleep: 3
      invalid: ['!']
  uut1:
    2:
      config: 'c3725'
      sleep: 3
      invalid: ['!']
  uut2:
    3:
      config: 'big-config'
      sleep: 3